# Generated by Django 4.0.4 on 2022-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlscanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='ipaddress',
        ),
        migrations.AddField(
            model_name='ip',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
