# Generated by Django 4.0.4 on 2022-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlscanner', '0003_fileupload_delete_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
                ('key', models.CharField(max_length=30)),
            ],
        ),
    ]
